/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchTeamsByCountryImport } from './routes/search-teams-by-country'
import { Route as SearchTeamByNameImport } from './routes/search-team-by-name'
import { Route as IndexImport } from './routes/index'
import { Route as TeamDetailTeamNameImport } from './routes/team-detail/$teamName'

// Create/Update Routes

const SearchTeamsByCountryRoute = SearchTeamsByCountryImport.update({
  id: '/search-teams-by-country',
  path: '/search-teams-by-country',
  getParentRoute: () => rootRoute,
} as any)

const SearchTeamByNameRoute = SearchTeamByNameImport.update({
  id: '/search-team-by-name',
  path: '/search-team-by-name',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeamDetailTeamNameRoute = TeamDetailTeamNameImport.update({
  id: '/team-detail/$teamName',
  path: '/team-detail/$teamName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/search-team-by-name': {
      id: '/search-team-by-name'
      path: '/search-team-by-name'
      fullPath: '/search-team-by-name'
      preLoaderRoute: typeof SearchTeamByNameImport
      parentRoute: typeof rootRoute
    }
    '/search-teams-by-country': {
      id: '/search-teams-by-country'
      path: '/search-teams-by-country'
      fullPath: '/search-teams-by-country'
      preLoaderRoute: typeof SearchTeamsByCountryImport
      parentRoute: typeof rootRoute
    }
    '/team-detail/$teamName': {
      id: '/team-detail/$teamName'
      path: '/team-detail/$teamName'
      fullPath: '/team-detail/$teamName'
      preLoaderRoute: typeof TeamDetailTeamNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search-team-by-name': typeof SearchTeamByNameRoute
  '/search-teams-by-country': typeof SearchTeamsByCountryRoute
  '/team-detail/$teamName': typeof TeamDetailTeamNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search-team-by-name': typeof SearchTeamByNameRoute
  '/search-teams-by-country': typeof SearchTeamsByCountryRoute
  '/team-detail/$teamName': typeof TeamDetailTeamNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/search-team-by-name': typeof SearchTeamByNameRoute
  '/search-teams-by-country': typeof SearchTeamsByCountryRoute
  '/team-detail/$teamName': typeof TeamDetailTeamNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search-team-by-name'
    | '/search-teams-by-country'
    | '/team-detail/$teamName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search-team-by-name'
    | '/search-teams-by-country'
    | '/team-detail/$teamName'
  id:
    | '__root__'
    | '/'
    | '/search-team-by-name'
    | '/search-teams-by-country'
    | '/team-detail/$teamName'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchTeamByNameRoute: typeof SearchTeamByNameRoute
  SearchTeamsByCountryRoute: typeof SearchTeamsByCountryRoute
  TeamDetailTeamNameRoute: typeof TeamDetailTeamNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchTeamByNameRoute: SearchTeamByNameRoute,
  SearchTeamsByCountryRoute: SearchTeamsByCountryRoute,
  TeamDetailTeamNameRoute: TeamDetailTeamNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/search-team-by-name",
        "/search-teams-by-country",
        "/team-detail/$teamName"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/search-team-by-name": {
      "filePath": "search-team-by-name.tsx"
    },
    "/search-teams-by-country": {
      "filePath": "search-teams-by-country.tsx"
    },
    "/team-detail/$teamName": {
      "filePath": "team-detail/$teamName.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
